version: '3.8'
services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 backend.main:app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data: