"""Add message_text to MessageLog

Revision ID: 070c90bff166
Revises: 7e3e9f177320
Create Date: 2024-09-29 11:51:08.752070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070c90bff166'
down_revision = '7e3e9f177320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_text', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_logs', schema=None) as batch_op:
        batch_op.drop_column('message_text')

    # ### end Alembic commands ###
