"""phone number data

Revision ID: 5041a0b5f341
Revises: 070c90bff166
Create Date: 2024-09-30 08:28:18.522645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5041a0b5f341'
down_revision = '070c90bff166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_logs', schema=None) as batch_op:
        batch_op.drop_column('sender_phone_number')

    # ### end Alembic commands ###
