"""Updates

Revision ID: d0c870efe078
Revises: 86fc263b31b5
Create Date: 2024-09-22 08:54:52.122844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c870efe078'
down_revision = '86fc263b31b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leadlandingpage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leadlandingpage', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
